/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.calculatorUI;

/**
 *
 * @author ForZa
 */
public class calculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form calculatorUI
     */
    public calculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        longVarSelector = new javax.swing.JComboBox<>();
        userInputLong = new javax.swing.JTextField();
        equalSign = new javax.swing.JLabel();
        convLongOutput = new javax.swing.JLabel();
        convertButtonShort = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        exampleLong = new javax.swing.JLabel();
        userInputShort = new javax.swing.JTextField();
        equalSign1 = new javax.swing.JLabel();
        convShortOutput = new javax.swing.JLabel();
        expampleShort = new javax.swing.JLabel();
        convertButtonLong = new javax.swing.JButton();
        comment1 = new javax.swing.JLabel();
        comment2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ET Rechner");

        longVarSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "T", "G", "M", "k", "", "m", "µ", "n" }));
        longVarSelector.setSelectedIndex(5);
        longVarSelector.setToolTipText("Kurzschreibweise auswählen");
        longVarSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longVarSelectorActionPerformed(evt);
            }
        });

        userInputLong.setToolTipText("Input number");

        equalSign.setText("=");

        convLongOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        convLongOutput.setText("0");

        convertButtonShort.setText("Umrechnen");
        convertButtonShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonShortActionPerformed(evt);
            }
        });

        exitButton.setText("Beenden");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        exampleLong.setForeground(new java.awt.Color(150, 150, 150));
        exampleLong.setText("Bsp.: 10k = 10000");

        userInputShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputShortActionPerformed(evt);
            }
        });

        equalSign1.setText("=");

        convShortOutput.setText("0");

        expampleShort.setForeground(new java.awt.Color(150, 150, 150));
        expampleShort.setText("Bsp.: 1000000 = 100k");

        convertButtonLong.setText("Umrechnen");
        convertButtonLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonLongActionPerformed(evt);
            }
        });

        comment1.setForeground(new java.awt.Color(75, 75, 75));
        comment1.setText("Tausenderseperator: ,");

        comment2.setForeground(new java.awt.Color(75, 75, 75));
        comment2.setText("Deizmalkomma: .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userInputLong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longVarSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equalSign)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(convLongOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exampleLong))
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userInputShort, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equalSign1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(convShortOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(convertButtonShort)
                                .addGap(458, 458, 458)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expampleShort)
                            .addComponent(convertButtonLong))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comment2)
                            .addComponent(comment1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInputLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longVarSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalSign)
                    .addComponent(convLongOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exampleLong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertButtonLong)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInputShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalSign1)
                    .addComponent(convShortOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expampleShort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertButtonShort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void longVarSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longVarSelectorActionPerformed
        convLongOutput.setText(my.calcultorBackEnd.shortToLong.convert(userInputLong.getText(), longVarSelector.getSelectedItem().toString()));
    }//GEN-LAST:event_longVarSelectorActionPerformed

    private void convertButtonShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonShortActionPerformed
        convShortOutput.setText(my.calcultorBackEnd.longToShort.convert(userInputShort.getText()));
    }//GEN-LAST:event_convertButtonShortActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void userInputShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputShortActionPerformed
        convShortOutput.setText(my.calcultorBackEnd.longToShort.convert(userInputShort.getText()));
    }//GEN-LAST:event_userInputShortActionPerformed

    private void convertButtonLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonLongActionPerformed
        convLongOutput.setText(my.calcultorBackEnd.shortToLong.convert(userInputLong.getText(), longVarSelector.getSelectedItem().toString()));
    }//GEN-LAST:event_convertButtonLongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment1;
    private javax.swing.JLabel comment2;
    private javax.swing.JLabel convLongOutput;
    private javax.swing.JLabel convShortOutput;
    private javax.swing.JButton convertButtonLong;
    private javax.swing.JButton convertButtonShort;
    private javax.swing.JLabel equalSign;
    private javax.swing.JLabel equalSign1;
    private javax.swing.JLabel exampleLong;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel expampleShort;
    private javax.swing.JComboBox<String> longVarSelector;
    private javax.swing.JTextField userInputLong;
    private javax.swing.JTextField userInputShort;
    // End of variables declaration//GEN-END:variables
}
